---
dependencies: []

galaxy_info:
  author: gerrive
  description: Docker Install for Debian/Ubuntu
  company: "Tetrasol"
  license: "license (MIT)"
  min_ansible_version: 1.9
  platforms:
    - name: Ubuntu
      versions:
      - all
    - name: Debian
      versions:
      - all
  galaxy_tags:
    - docker
