---
- name: Remove old docker-engine
  apt: pkg={{item}} state=removed
  with_items: "{{ docker_remove_packages }}"

- name: Install Docker Engine Dependecies
  apt: pkg={{item}} update_cache=true
  with_items: "{{ docker_packages }}"


- name: Configure Docker pkg Auth
  apt_key: keyserver={{docker_keyserver}}
           id=58118E89F3A912897C070ADBF76221572C52609D
           state=present

- name: Add current docker entry
  apt_repository: repo="deb https://apt.dockerproject.org/repo {{ansible_distribution|lower}}-{{ansible_distribution_release}} main"
                  state=present

- name: Install Docker Engine
  apt: pkg=docker-engine state=present update_cache=true
  become: true

- name: Docker Service Configuration
  template: src=docker.j2 dest=/etc/default/docker
  notify:
    - Restart Docker Service

- name: User Docker Permissions
  become: yes
  user: name={{docker_user}} group=docker
  notify:
    - Restart Docker Service

- name: Install Docker compose
  become: yes
  pip: name=docker-compose version=1.8.1

- name: Install DockerPy
  pip: name=docker-py version=1.9
